mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: debug
spring:
  freemarker:
    charset: UTF-8
    suffix: .ftl
    content-type: text/html; charset=utf-8
    template-loader-path: classpath:/ftl/
    cache: false
config:
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: root
  jdbcUrl: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
